`twmo`: validation and source code for twmo in tropopause
eagles-project/mam4xx pull request #270
Opened 2023-12-08 01:02 UTC by jaelynlitz

instead of #258

2023-12-08 02:33 UTC, odiazib requested changes

2023-12-08 02:33 UTC, odiazib commented on src/validation/tropopause/twmo.cpp
> +
We need to add kokkos:parallel_for.

2023-12-08 02:48 UTC, odiazib commented on src/validation/tropopause/twmo.cpp
> +
We need a` Kokkos::parallel_for` because this computation will be done in the GPU.

2023-12-11 16:55 UTC, jeff-cohere approved these changes

2023-12-11 18:09 UTC, odiazib approved these changes

2023-12-11 18:11 UTC, jaelynlitz commented
Thanks all! Merging 😄

2023-12-11 18:12 UTC, merged